name: help_scout_beacon
description: "Streamline customer communications in your app with the Help Scout Beacon SDK for Flutter."
version: 0.0.3
repository: https://github.com/coodoo-io/help_scout_beacon
issue_tracker: https://github.com/coodoo-io/help_scout_beacon/issues

topics:
  - customer
  - helpdesk
  - support
  - help

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  pigeon: ^17.0.0

flutter:
  plugin:
    platforms:
      android:
        package: de.coodoo.help_scout_beacon
        pluginClass: HelpScoutBeaconPlugin
      ios:
        pluginClass: HelpScoutBeaconPlugin
